/** @type {import('tailwindcss').Config} */
// Mapeo de los tokens de src/styles/tokens.css. Aquí no se define ningún valor nuevo:
// si un color, un espacio o una duración no está en tokens.css, no existe para Tailwind.
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['class', '[data-tema="oscuro"]'],
  theme: {
    extend: {
      colors: {
        fondo: 'var(--color-fondo)',
        superficie: 'var(--color-superficie)',
        'superficie-2': 'var(--color-superficie-2)',
        borde: 'var(--color-borde)',
        'borde-fuerte': 'var(--color-borde-fuerte)',
        tinta: 'var(--color-tinta)',
        'tinta-suave': 'var(--color-tinta-suave)',
        'tinta-tenue': 'var(--color-tinta-tenue)',
        primario: 'var(--color-primario)',
        'primario-fuerte': 'var(--color-primario-fuerte)',
        'primario-suave': 'var(--color-primario-suave)',
        'sobre-primario': 'var(--color-sobre-primario)',
        acento: 'var(--color-acento)',
        'acento-texto': 'var(--color-acento-texto)',
        'acento-suave': 'var(--color-acento-suave)',
        'sobre-acento': 'var(--color-sobre-acento)',
        exito: 'var(--color-exito)',
        'exito-suave': 'var(--color-exito-suave)',
        atencion: 'var(--color-atencion)',
        'atencion-suave': 'var(--color-atencion-suave)',
        error: 'var(--color-error)',
        'error-suave': 'var(--color-error-suave)',
        'sobre-estado': 'var(--color-sobre-estado)',
        foco: 'var(--color-foco)',
        velo: 'var(--color-velo)',
        'serie-a': 'var(--color-serie-a)',
        'serie-b': 'var(--color-serie-b)',
        referencia: 'var(--color-referencia)',
      },
      fontFamily: {
        titulo: 'var(--fuente-titulo)',
        cuerpo: 'var(--fuente-cuerpo)',
        sans: 'var(--fuente-cuerpo)',
      },
      fontSize: {
        micro: ['var(--texto-micro)', { lineHeight: '1.4' }],
        chico: ['var(--texto-chico)', { lineHeight: '1.45' }],
        base: ['var(--texto-base)', { lineHeight: 'var(--interlinea-cuerpo)' }],
        md: ['var(--texto-md)', { lineHeight: 'var(--interlinea-titulo)' }],
        lg: ['var(--texto-lg)', { lineHeight: 'var(--interlinea-titulo)' }],
        xl: ['var(--texto-xl)', { lineHeight: 'var(--interlinea-titulo)' }],
        '2xl': ['var(--texto-2xl)', { lineHeight: 'var(--interlinea-titulo)' }],
        '3xl': ['var(--texto-3xl)', { lineHeight: 'var(--interlinea-titulo)' }],
      },
      fontWeight: {
        normal: 'var(--peso-cuerpo)',
        medium: 'var(--peso-medio)',
        semibold: 'var(--peso-medio)',
        bold: 'var(--peso-titulo)',
      },
      spacing: {
        1: 'var(--esp-1)',
        2: 'var(--esp-2)',
        3: 'var(--esp-3)',
        4: 'var(--esp-4)',
        5: 'var(--esp-5)',
        6: 'var(--esp-6)',
        8: 'var(--esp-8)',
        10: 'var(--esp-10)',
        12: 'var(--esp-12)',
        16: 'var(--esp-16)',
        toque: 'var(--toque-minimo)',
      },
      borderRadius: {
        chico: 'var(--radio-chico)',
        tarjeta: 'var(--radio-tarjeta)',
        hoja: 'var(--radio-hoja)',
        lleno: 'var(--radio-lleno)',
        xl2: 'var(--radio-tarjeta)',
      },
      boxShadow: {
        1: 'var(--sombra-1)',
        2: 'var(--sombra-2)',
        3: 'var(--sombra-3)',
      },
      transitionDuration: {
        rapida: 'var(--dur-rapida)',
        estado: 'var(--dur-estado)',
        entrada: 'var(--dur-entrada)',
      },
      transitionTimingFunction: {
        entrada: 'var(--curva-entrada)',
        salida: 'var(--curva-salida)',
      },
      maxWidth: { contenido: 'var(--ancho-contenido)' },
      screens: { xs: '360px' },
    },
  },
  plugins: [],
}
